apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bjma9u8da-nodejs
  janus-idp.io/tekton: bjma9u8da-nodejs
  backstage.io/kubernetes-id: bjma9u8da-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bjma9u8da-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
