apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bjma9u8da-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:8b4b2aaed882b5dbbc8ceb1966057dbc2eb29cc8@sha256:4962a0b3d85c8e27ffa6f28c6c53585a7953a10b2a5e364d8ebedad844e42869
          name: container-image
